services:

  controlnode:
    build:
      context: control-node/
    image: ansible:controlnode
    working_dir: /playbooks
    user: 'root'
    volumes:
      - ./secrets:/secrets
      - ./playbooks:/playbooks
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: 'tail -f /dev/null'
  
  managedhost-alpine:
    build: managed-hosts/alpine/
    restart: unless-stopped
    volumes:
      - ./secrets/id_rsa.pub:/root/.ssh/authorized_keys
    ports:
    - 3210:3000
    environment:
      - SSH_ENBABLE_ROOT=true